// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MscJobsForDisabled.InfrastructureServices.Gateways.Database;

namespace MscJobsForDisabled.WebService.Migrations
{
    [DbContext(typeof(JobContext))]
    [Migration("20200531214737_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("MscJobsForDisabled.DomainObjects.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "arina.donich@nami.ru  ",
                            Location = "город Москва, Автомоторная улица, дом 2",
                            Name = "Инженер-программист",
                            Telephone = "(495) 456-43-51",
                            WorkingHours = "пятидневная рабочая неделя "
                        },
                        new
                        {
                            Id = 2L,
                            Email = "arina.donich@nami.ru  ",
                            Location = "город Москва, Автомоторная улица, дом 2",
                            Name = "Инженер-конструктор",
                            Telephone = "(495) 456-43-51",
                            WorkingHours = "пятидневная рабочая неделя "
                        },
                        new
                        {
                            Id = 3L,
                            Email = "tishumilina@rolf.ru",
                            Location = "город Москва, 39-й километр Московской Кольцевой Автодороги, владение 1, строение 1",
                            Name = "Продавец-консультант",
                            Telephone = "(495) 777-77-15 доб. 30171",
                            WorkingHours = "график сменности  "
                        },
                        new
                        {
                            Id = 4L,
                            Email = "MGorbacheva@nestro.ru ",
                            Location = "город Москва, Армянский переулок, дом 9, строение 1 ",
                            Name = "Переводчик",
                            Telephone = "(495) 748-64-24 доб. 1008 ",
                            WorkingHours = "с неполным рабочим днем"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
